import Link from "next/link";
import { getSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { createRewardItem, deleteRewardItem, purchaseRewardItem } from "./actions";

export default async function RewardsPage({ searchParams }: { searchParams: Promise<{ notice?: string }> }) {
  const [{ notice }, session] = await Promise.all([searchParams, getSession()]);
  const [passedTasks, spent, items, purchases] = await Promise.all([
    prisma.submission.findMany({ where: { passed: true }, distinct: ["taskId"], select: { taskId: true } }),
    prisma.rewardPurchase.aggregate({ _sum: { pricePaid: true } }),
    prisma.rewardItem.findMany({ where: session.role === "teacher" ? undefined : { isActive: true }, orderBy: { createdAt: "desc" } }),
    prisma.rewardPurchase.findMany({ orderBy: { purchasedAt: "desc" }, include: { rewardItem: { select: { title: true } } }, take: 8 }),
  ]);
  const available = passedTasks.length - (spent._sum.pricePaid ?? 0);
  const isTeacher = session.role === "teacher";
  return <div className="space-y-6">
    <section className="course-grid glass-surface rounded-2xl border-blue-100/70 p-5 sm:p-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Награды</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-heading text-3xl font-bold text-ink">Магазин</h1><p className="mt-2 max-w-xl text-ink-soft">Звезды даются за правильно выполненные задания. Один пройденный номер - одна звезда.</p></div>{!isTeacher && <div className="rounded-xl bg-slate-950 px-4 py-3 text-white"><span className="text-sm text-slate-300">Доступно</span><p className="text-2xl font-bold">★ {available}</p></div>}</div></section>
    {notice && <p className="rounded-xl border border-blue-200 bg-primary-soft px-4 py-3 text-sm font-bold text-primary">{notice}</p>}
    {isTeacher && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.14em] text-ink-soft">Учитель</p><h2 className="mt-1 font-heading text-xl font-bold text-ink">Создать предмет</h2><form action={createRewardItem} className="mt-5 grid gap-3 md:grid-cols-2"><input name="title" required placeholder="Название предмета" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-primary md:col-span-2" /><input name="description" placeholder="Короткое описание" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-primary md:col-span-2" /><label className="text-sm font-bold text-ink">Цена в звездах<input name="price" type="number" min="1" required className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 font-normal outline-none focus:border-primary" /></label><label className="text-sm font-bold text-ink">Количество покупок<input name="stock" type="number" min="1" required className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 font-normal outline-none focus:border-primary" /></label><button type="submit" className="rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-white transition hover:bg-primary-dark md:col-span-2">Создать предмет</button></form></section>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.length === 0 ? <p className="rounded-xl border border-dashed border-slate-300 bg-white p-7 text-center text-sm text-ink-soft sm:col-span-2 xl:col-span-3">В магазине пока нет предметов.</p> : items.map((item) => { const canBuy = !isTeacher && item.isActive && item.stock > 0 && available >= item.price; const buy = purchaseRewardItem.bind(null, item.id); const remove = deleteRewardItem.bind(null, item.id); return <article key={item.id} className={`flex min-h-48 flex-col justify-between rounded-2xl border bg-white p-5 shadow-sm ${item.isActive ? "border-slate-200" : "border-slate-200 opacity-60"}`}><div><div className="flex items-start justify-between gap-3"><h2 className="font-heading text-lg font-bold text-ink">{item.title}</h2><span className="rounded-lg bg-yellow-soft px-2.5 py-1 text-sm font-bold text-ink">★ {item.price}</span></div>{item.description && <p className="mt-3 text-sm leading-6 text-ink-soft">{item.description}</p>}{isTeacher && !item.isActive && <p className="mt-3 text-xs font-bold text-ink-soft">Удален из витрины</p>}</div><div className="mt-5 flex items-center justify-between gap-3 border-t border-slate-100 pt-3"><span className="text-sm font-bold text-ink-soft">Осталось: {item.stock}</span>{isTeacher ? <form action={remove}><button disabled={!item.isActive} className="rounded-lg px-3 py-2 text-sm font-bold text-danger transition hover:bg-danger-soft disabled:cursor-not-allowed disabled:text-slate-400">{item.isActive ? "Удалить" : "Удален"}</button></form> : <form action={buy}><button disabled={!canBuy} className="rounded-lg bg-primary px-3 py-2 text-sm font-bold text-white transition hover:bg-primary-dark disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-500">{item.stock < 1 ? "Нет в наличии" : available < item.price ? "Не хватает звезд" : "Купить"}</button></form>}</div></article>; })}</section>
    {isTeacher && purchases.length > 0 && <section className="space-y-3 border-t border-slate-200 pt-6"><h2 className="font-heading text-xl font-bold text-ink">Последние покупки</h2><ul className="space-y-2">{purchases.map((purchase) => <li key={purchase.id} className="flex flex-wrap justify-between gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><span className="font-bold text-ink">{purchase.rewardItem.title}</span><span className="text-ink-soft">★ {purchase.pricePaid} · {new Date(purchase.purchasedAt).toLocaleDateString("ru-RU")}</span></li>)}</ul></section>}
    <Link href="/profile" className="inline-flex text-sm font-bold text-ink-soft transition hover:text-primary">← Вернуться в My Study</Link>
  </div>;
}
